// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Authentication struct {
	AuthenticationID     int64          `json:"authentication_id"`
	ProfileID            int64          `json:"profile_id"`
	Secret               string         `json:"secret"`
	Status               string         `json:"status"`
	Email                string         `json:"email"`
	Name                 string         `json:"name"`
	OldPassword          sql.NullString `json:"old_password"`
	Password             string         `json:"password"`
	PasswordConfirmation sql.NullString `json:"password_confirmation"`
	PhoneNumber          string         `json:"phone_number"`
	RequestType          sql.NullString `json:"request_type"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type Profile struct {
	ProfileID    int64          `json:"profile_id"`
	Username     string         `json:"username"`
	NamaLengkap  string         `json:"nama_lengkap"`
	Email        string         `json:"email"`
	Telephone    string         `json:"telephone"`
	UserPassword sql.NullString `json:"user_password"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	IsBanned     sql.NullBool   `json:"is_banned"`
	Token        sql.NullString `json:"token"`
	RoleID       int64          `json:"role_id"`
	Status       string         `json:"status"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CreatedBy    string         `json:"created_by"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedBy    sql.NullString `json:"updated_by"`
}

type Role struct {
	RoleID    int64          `json:"role_id"`
	RoleName  string         `json:"role_name"`
	Status    string         `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
	CreatedBy string         `json:"created_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
}
